<a href="https://colab.research.google.com/github/AhsanDz/4-Ahsan-Clara/blob/main/Data%20Cleaning_Clara.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# GDGoC ML Study Jam - Chapter 1 Challenge
## **Topic: The Smartphone Analyst**

Selamat datang, Data Detective! 🕵️‍♂️

Hari ini, kita tidak hanya belajar koding, tapi belajar **memecahkan masalah menggunakan data**.

**Skenario:**
Kamu adalah Lead Data Analyst di sebuah toko gadget besar. Bosmu memberikan dataset spesifikasi smartphone dan memintamu menjawab **10 Pertanyaan Bisnis** untuk strategi penjualan bulan depan.

**Aturan Main:**
1.  **Bebas Berkreasi:** Gunakan metode apapun (Filtering, Sorting, Grouping, atau Visualisasi Grafik).
2.  **Wajib Ada Insight:** Setelah kode dijalankan, tulis kesimpulanmu di cell Teks di bawahnya.
3.  **Have Fun!**

In [ ]:
# ⚠️ JALANKAN CELL INI TERLEBIH DAHULU!
# Script ini akan membuat dataset dummy untuk latihan kita hari ini.

import pandas as pd
import numpy as np
import random

np.random.seed(42)

# Data Dummy
n_data = 150
brands = ['Samsung', 'Apple', 'Xiaomi', 'Oppo', 'Vivo', 'Realme', 'Infinix', 'Asus', 'Google']
rams = [4, 6, 8, 12, 16, 24] # Ada RAM 24GB buat gaming
storages = [64, 128, 256, 512, 1024]

data = {
    'Brand': [random.choice(brands) for _ in range(n_data)],
    'Model': [f"Phone {i}" for i in range(n_data)],
    'RAM_GB': [random.choice(rams) for _ in range(n_data)],
    'Storage_GB': [random.choice(storages) for _ in range(n_data)],
    'Rating': [round(random.uniform(3.0, 5.0), 1) for _ in range(n_data)]
}

df = pd.DataFrame(data)

# Bikin harga agak logis -> (RAM gede + Storage gede = Mahal) + sedikit random noise
df['Price_Juta'] = (df['RAM_GB'] * 0.5) + (df['Storage_GB'] * 0.015) + np.random.randint(1, 4, n_data)
df['Price_Juta'] = df['Price_Juta'].round(1)

# Tambahin Data -> "Aneh" (Anomaly)
df.loc[148] = ['Nokia', 'Nokia 3310 Reborn', 2, 16, 50.0, 5.0] # HP kentang harga sultan
df.loc[149] = ['Unknown', 'Prototype X', 128, 2048, 0.5, 1.0] # Spek dewa harga permen

print("Dataset 'smartphones' berhasil dibuat!")
print(f"Total Data: {len(df)} baris.")
df.head(10)

Dataset 'smartphones' berhasil dibuat!
Total Data: 150 baris.


,Brand,Model,RAM_GB,Storage_GB,Rating,Price_Juta
0,Vivo,Phone 0,16,256,4.9,14.8
1,Asus,Phone 1,6,128,4.8,5.9
2,Realme,Phone 2,4,512,3.7,12.7
3,Google,Phone 3,16,64,4.8,12.0
4,Vivo,Phone 4,8,128,4.6,6.9
5,Realme,Phone 5,12,128,4.5,8.9
6,Infinix,Phone 6,6,64,5.0,7.0
7,Asus,Phone 7,12,128,3.7,9.9
8,Samsung,Phone 8,8,128,3.3,8.9
9,Asus,Phone 9,4,1024,3.6,20.4


---
### **Quest 1: Cek Ombak (Overview)**
Sebelum masuk ke analisis dalam, coba cek dulu isi gudang kita.
1. Ada berapa baris dan kolom di data ini?
2. Apa saja nama kolomnya?
3. Tampilkan statistik dasarnya (Rata-rata, Max, Min).

*Hint: Gunakan `.shape`, `.columns`, dan `.describe()`.*

In [ ]:
print(df.shape)
print(df.columns)
print(df.describe())

(150, 6)
Index(['Brand', 'Model', 'RAM_GB', 'Storage_GB', 'Rating', 'Price_Juta'], dtype='object')
           RAM_GB   Storage_GB      Rating  Price_Juta
count  150.000000   150.000000  150.000000  150.000000
mean    12.413333   441.706667    4.428000   14.282667
std     11.910847   374.435227    3.798748    6.798991
min      2.000000    16.000000    0.500000    1.000000
25%      6.000000   128.000000    3.700000    8.900000
50%      8.000000   256.000000    4.250000   12.800000
75%     16.000000   512.000000    4.600000   19.400000
max    128.000000  2048.000000   50.000000   30.400000


1. Ada berapa baris dan kolom di data ini? Data ini terdiri dari 150 baris dan 6 kolom. Identitas ini dapat diakses melalui df.shape
2. Apa saja nama kolomnya?
Melalui df.columns, diketahui bahwa 6 kolom pada data memiliki nama masing-masing. Diantaranya adalah 'Brand', 'Model', 'RAM_GB', 'Storage_GB', 'Rating', 'Price_Juta'
3. Tampilkan statistik dasarnya (Rata-rata, Max, Min).
Untuk menampilkan statistik data, digunakan function df.describe(). Didapatkan mean, max, dan min dari setiap kolom yang memiliki nilai bertipe integer atau float seperti tabel di atas.

---
### **Quest 2: Raja Pasar**
Brand apa yang paling banyak memiliki model HP dalam daftar ini?

*Hint: Gunakan `.value_counts()`.*

In [ ]:
data = df['Brand'].value_counts()
print(data)
max = data.max()
print(f'Brand dengan jumlah model HP terbanyak dengan jumlah {max} buah adalah', data.idxmax())

Brand
Apple      24
Samsung    22
Infinix    18
Oppo       17
Xiaomi     16
Vivo       16
Asus       15
Google     12
Realme      8
Nokia       1
Unknown     1
Name: count, dtype: int64
Brand dengan jumlah model HP terbanyak dengan jumlah 24 buah adalah Apple


Untuk mengetahui brand dengan model terbanyak, digunakan function .value_counts() pada kolom brand. Didapatkan bahwa brand Xiaomi memiliki 21 model. Maka dapat disimpulkan bahwa brand Xiaomi adalah brand dengan model HP terbanyak dari data tersebut.



---
### **Quest 3: Storage Wars**
Zaman sekarang aplikasi makin besar.
Coba cari HP yang punya **Storage paling besar** (Max Storage). Ada berapa HP yang punya storage segitu?

*Hint: Cari nilai max dulu, lalu filter datanya.*

In [ ]:
data_real = df[df['Storage_GB'].isin(storages)]
max_storage = data_real['Storage_GB'].max()
print('Storage Paling Besar:', max_storage, 'GB')

a = data_real['Storage_GB'].value_counts()
print('Berikut adalah rincian jumlah brand HP berdasarkan penyimpanannya: ')
print(a)

jumlah_1024 = a[max_storage]
print()
print(f'Terdapat {jumlah_1024} HP dengan storage sebesar {max_storage} GB')
list_brand = data_real[data_real['Storage_GB'] == max_storage]
print(f'Berikut adalah rincian brand HP dengan penyimpanan terbesar, yakni sebanyak {jumlah_1024} buah')
print(list_brand)

Storage Paling Besar: 1024 GB
Berikut adalah rincian jumlah brand HP berdasarkan penyimpanannya: 
Storage_GB
512     39
1024    32
128     27
256     25
64      25
Name: count, dtype: int64

Terdapat 32 HP dengan storage sebesar 1024 GB
Berikut adalah rincian brand HP dengan penyimpanan terbesar, yakni sebanyak 32 buah
       Brand      Model  RAM_GB  Storage_GB  Rating  Price_Juta
9       Asus    Phone 9       4        1024     3.6        20.4
10     Apple   Phone 10      12        1024     3.1        24.4
11   Infinix   Phone 11      16        1024     4.7        26.4
14      Oppo   Phone 14       4        1024     3.9        19.4
15   Samsung   Phone 15       8        1024     3.9        20.4
23    Xiaomi   Phone 23      12        1024     4.5        23.4
30   Infinix   Phone 30       4        1024     3.6        19.4
33      Oppo   Phone 33      24        1024     3.5        29.4
60    Google   Phone 60      12        1024     3.4        23.4
61   Infinix   Phone 61      24        

Berdasarkan cell di atas, diketahui bahwa ada data anomali. Maka, kita melakukan filter data dengan membuat variabel `data_real` dan menggunakan function .isin() untuk menampung data-data yang sesuai dengan nilai storages.

Selanjutnya, cell ini dikerjakan dengan menggunakan variabel data_real. Didapatkan juga detail jumlah HP dengan penyimpanan tertentu.

Setelah itu, kita melakukan filter untuk mencari data-data HP yang memiliki penyimpanan 1024 GB. Kemudian data tersebut dicetak

---
### **Quest 4: Budget vs Premium**
Bos ingin tahu rentang harga pasar.
1. Berapa harga HP **termurah**?
2. Berapa harga HP **termahal**?

*Hint: Gunakan `.min()` dan `.max()` pada kolom harga.*

In [ ]:
# Data anomali belum disaring

min = df['Price_Juta'].min()
max = df['Price_Juta'].max()
print('Harga HP termurah:', min, 'juta')
print('Harga HP termahal:', max, 'juta')

# Kode dengan data anomali yang sudah disaring

data_real = df[
    ~((df['RAM_GB'] < 4) & (df['Price_Juta'] > 10)) & # Hapus jika RAM < 4 DAN Harga > 10
    ~((df['RAM_GB'] > 32) & (df['Price_Juta'] < 5)) & # Hapus jika RAM > 32 DAN Harga < 5
    ~(df['Rating'] > 5)
]

urutan_harga = data_real['Price_Juta'].value_counts()
min_baru = data_real['Price_Juta'].min()
max_baru = data_real['Price_Juta'].max()
tmp_min = urutan_harga[min_baru]
tmp_max = urutan_harga[max_baru]
list_min = data_real[data_real['Price_Juta'] == min_baru]
list_max = data_real[data_real['Price_Juta'] == max_baru]
print()
print(f'Harga HP termurah dengan data baru: {min_baru} juta. Terdapat {tmp_min} HP dengan harga {min_baru} juta, yakni:')
print(list_min)
print()
print(f'Harga HP termahal dengan data baru: {max_baru} juta. Terdapat {tmp_max} HP dengan harga {max_baru} juta, yakni:')
print(list_max)


Harga HP termurah: 1.0 juta
Harga HP termahal: 30.4 juta

Harga HP termurah dengan data baru: 4.0 juta. Terdapat 3 HP dengan harga 4.0 juta, yakni:
       Brand      Model  RAM_GB  Storage_GB  Rating  Price_Juta
25      Vivo   Phone 25       4          64     3.9         4.0
38      Oppo   Phone 38       4          64     4.2         4.0
112  Samsung  Phone 112       4          64     3.8         4.0

Harga HP termahal dengan data baru: 30.4 juta. Terdapat 2 HP dengan harga 30.4 juta, yakni:
      Brand     Model  RAM_GB  Storage_GB  Rating  Price_Juta
86  Samsung  Phone 86      24        1024     4.8        30.4
97     Oppo  Phone 97      24        1024     3.2        30.4


Kode paling atas berfungsi untuk menemukan data harga HP termurah dan harga HP termahal dengan data anomali yang belum disaring

Sementara itu, kode di bawah berfungsi untuk menemukan data harga HP termurah dan termahal dengan data anomali yang sudah disaring. data_real adalah variabel yang digunakan untuk menampung data yang bersih. Maka dari itu, kode dibawahnya selalu menggunakan variabel ini.

---
### **Quest 5: The Gaming Beast**
Seorang Gamer datang mencari HP. Syaratnya mutlak:
1. **RAM wajib di atas 12 GB.**
2. **Storage minimal 512 GB.**

Tampilkan daftar HP yang memenuhi syarat tersebut!

*Hint: Gunakan Filtering dengan logika AND (`&`).*

In [ ]:
data_bersyarat = data_real[
    (data_real['RAM_GB'] > 12) & (data_real['Storage_GB'] >= 512)
]
total = len(data_bersyarat)

print(f'Terdapat {total} HP yang memenuhi syarat untuk gamer tersebut. Diantaranya adalah: ')
print(data_bersyarat)

Terdapat 26 HP yang memenuhi syarat untuk gamer tersebut. Diantaranya adalah: 
       Brand      Model  RAM_GB  Storage_GB  Rating  Price_Juta
11   Infinix   Phone 11      16        1024     4.7        26.4
13   Samsung   Phone 13      24         512     4.9        22.7
20    Google   Phone 20      24         512     4.6        20.7
22    Xiaomi   Phone 22      24         512     4.9        21.7
31    Realme   Phone 31      16         512     3.2        18.7
33      Oppo   Phone 33      24        1024     3.5        29.4
43      Asus   Phone 43      24         512     3.1        20.7
61   Infinix   Phone 61      24        1024     4.0        28.4
63    Xiaomi   Phone 63      24         512     4.6        21.7
64     Apple   Phone 64      24        1024     4.5        29.4
70      Oppo   Phone 70      24         512     4.3        22.7
72    Google   Phone 72      24         512     3.9        21.7
78   Samsung   Phone 78      16        1024     3.6        26.4
83     Apple   Phone 83  

Untuk mendapatkan data HP sesuai syarat tersebut, digunakan logika AND. Disini, digunakan data_real karena variabel ini menyimpan data yang sudah disaring di cell sebelumnya.

Kemudian, variabel total digunakan untuk menampung jumlah HP yang memenuhi syarat dan daftar HP tersebut dicetak.

---
### **Quest 6: Sobat Mahasiswa**
Mahasiswa biasanya cari HP yang "Worth it".
Cari HP yang harganya **di bawah 7 Juta**, TAPI **Rating-nya di atas 4.5**.

Ada nggak barangnya?

In [ ]:
hp_mahasiswa = data_real[
    (data_real['Price_Juta'] < 7) & (data_real['Rating'] > 4.5)
]
jumlah_hp = len(hp_mahasiswa)

print(f'Terdapat {jumlah_hp} HP yang sesuai dengan kriteria mahasiswa. Diantaranya adalah: ')
print(hp_mahasiswa)

Terdapat 4 HP yang sesuai dengan kriteria mahasiswa. Diantaranya adalah: 
     Brand     Model  RAM_GB  Storage_GB  Rating  Price_Juta
1     Asus   Phone 1       6         128     4.8         5.9
4     Vivo   Phone 4       8         128     4.6         6.9
24  Google  Phone 24       4         128     5.0         4.9
71    Oppo  Phone 71       4         128     4.6         5.9


Untuk menjalankan kode ini, digunakan variabel data_real yang sudah bersih dari data anomali.

Variabel hp_mahasiswa digunakan untuk menyimpan data dengan kriteria harga di bawah 7 juta dan rating di atas 4.5. Maka dari itu, digunakan operasi AND (&) agar kedua kondisi terpenuhi

Menggunakan len(), variabel jumlah_hp digunakan untuk menampung jumlah HP yang sesuai dengan kriteria tersebut. Kemudian hp_mahasiswa dicetak.

---
### **Quest 7: Fanboy Apple**
Ada pelanggan yang cuma mau beli **Apple**.
Tampilkan semua HP merk Apple, lalu urutkan dari yang **paling mahal ke paling murah**.

*Hint: Filter `Brand == 'Apple'`, lalu `sort_values`.*

In [ ]:
data_apple = data_real[data_real['Brand'] == 'Apple']
harga_apple = data_apple.sort_values(by='Price_Juta', ascending=False)
jumlah_apple = len(data_apple)
print(f'Terdapat {jumlah_apple} HP merk Apple. Berikut adalah harga HP Apple yang telah diurutkan: ')
print(harga_apple)

Terdapat 24 HP merk Apple. Berikut adalah harga HP Apple yang telah diurutkan: 
     Brand      Model  RAM_GB  Storage_GB  Rating  Price_Juta
64   Apple   Phone 64      24        1024     4.5        29.4
83   Apple   Phone 83      24        1024     4.8        28.4
10   Apple   Phone 10      12        1024     3.1        24.4
118  Apple  Phone 118       8        1024     4.4        22.4
120  Apple  Phone 120       6        1024     3.8        19.4
108  Apple  Phone 108       4        1024     3.3        18.4
94   Apple   Phone 94      24         256     3.1        16.8
52   Apple   Phone 52      16         256     4.8        13.8
74   Apple   Phone 74       8         512     4.2        13.7
85   Apple   Phone 85      16         128     4.1        11.9
57   Apple   Phone 57       6         512     4.1        11.7
53   Apple   Phone 53       4         512     4.2        10.7
122  Apple  Phone 122       8         256     4.2         9.8
109  Apple  Phone 109      12          64     3.7   

data_apple digunakan untuk menampung data HP dengan brand Apple.

harga_apple digunakan untuk menampung urutan HP berdasarkan harga mulai harga paling mahal ke murah. `data_apple.sort_values(by='Price_Juta', ascending=False)` adalah syntax untuk menyaring kolom Price_Juta dari terbesar ke terkecil. Jika tidak ditambahkan ascending=false, maka variabel ini menampung data dengan urutan data termurah ke termahal.

---
### **Quest 8: Rata-Rata Harga per Brand (Level Medium)**
Brand mana yang rata-rata harga produknya paling mahal?
Coba hitung rata-rata harga (`Price_Juta`) untuk setiap `Brand`.

*Hint: Ini butuh Grouping. Gunakan `.groupby('Brand')['Price_Juta'].mean()`.*

In [ ]:
rata_rata_harga = data_real.groupby('Brand')['Price_Juta'].mean()
rata_rata_terbesar = rata_rata_harga.max()
brand_termahal = rata_rata_harga.idxmax()
print(rata_rata_harga)
print(f'Brand dengan rata-rata harga produk paling mahal adalah {brand_termahal} dengan rata-rata mencapai {rata_rata_terbesar} juta')

Brand
Apple      13.025000
Asus       14.300000
Google     13.583333
Infinix    15.444444
Oppo       15.617647
Realme     12.837500
Samsung    15.886364
Vivo       14.362500
Xiaomi     13.800000
Name: Price_Juta, dtype: float64
Brand dengan rata-rata harga produk paling mahal adalah Samsung dengan rata-rata mencapai 15.886363636363637 juta


Dengan menggunakan function .groupby('Brand')['Price_Juta'].mean(), kita membuat series dengan Brand sebagai indexnya. Dengan menggunakan .mean(), kita menghitung Price_Juta pada index yang sama.

Dengan .max() dan .idxmax(), kita mengambil nilai terbesar dan index terbesar dari series tersebut, kemudian dicetak.

---
### **Quest 9: Value for Money (Feature Engineering)**
Kita mau cari HP yang "Spek Dewa Harga Kaki Lima".
1. Buat kolom baru bernama `Skor_Performa` = `RAM_GB` + `Storage_GB`.
2. Buat kolom baru bernama `Value_Skor` = `Skor_Performa` / `Price_Juta`.
3. Tampilkan 5 HP dengan `Value_Skor` tertinggi.

*Hint: Kamu bisa melakukan operasi matematika antar kolom secara langsung.*

In [ ]:
data_real['Skor_Performa'] = data_real['RAM_GB'] + data_real['Storage_GB']
data_real['Value_Skor'] = data_real['Skor_Performa'] / data_real['Price_Juta']
data_spekdewa = data_real.sort_values(by='Value_Skor', ascending=False)
print(data_spekdewa.head())

       Brand      Model  RAM_GB  Storage_GB  Rating  Price_Juta  \
108    Apple  Phone 108       4        1024     3.3        18.4   
127  Infinix  Phone 127       4        1024     3.6        18.4   
120    Apple  Phone 120       6        1024     3.8        19.4   
91   Samsung   Phone 91       6        1024     4.2        19.4   
14      Oppo   Phone 14       4        1024     3.9        19.4   

     Skor_Performa  Value_Skor  
108           1028   55.869565  
127           1028   55.869565  
120           1030   53.092784  
91            1030   53.092784  
14            1028   52.989691  


/tmp/ipython-input-257180074.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_real['Skor_Performa'] = data_real['RAM_GB'] + data_real['Storage_GB']
/tmp/ipython-input-257180074.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_real['Value_Skor'] = data_real['Skor_Performa'] / data_real['Price_Juta']


Kita membuat kolom baru bernama Skor_Performa dan Value_Skor. Hal ini perlu dilakukan karena kita akan melakukan sortir pada kolom Value_Skor. Dengan menambahkan ascending=False, data telah diurutkan dari yang terbesar ke yang terkecil.

5 data teratas dicetak menggunakan .head()

Muncul peringatan setelah kode dijalankan. Hal ini dikarenakan kita bekerja pada slice dari data yang asli.

---
### **Quest 10: The Detective (Final Boss)**
Ada laporan data error di sistem.
1. Cari HP yang harganya **di atas 40 Juta** (Kemahalan/Mustahil).
2. Cari HP yang harganya **di bawah atau sama dengan 1 Juta** tapi RAM-nya **di atas 100 GB** (Ngawur).

Temukan data penyusup ini!

*Hint: Gunakan filtering untuk mencari outlier.*

In [ ]:
data_penyusup = df[(df['Price_Juta'] > 40) | ((df['Price_Juta'] <= 1) & (df['RAM_GB'] > 100))]
kolom = ['Brand', 'Model', 'RAM_GB', 'Storage_GB', 'Rating', 'Price_Juta']
print(data_penyusup[kolom])


       Brand        Model  RAM_GB  Storage_GB  Rating  Price_Juta
149  Unknown  Prototype X     128        2048     0.5         1.0


Untuk menemukan data penyusup ini, kita tidak bisa menggunakan data_real. Hal ini dikarenakan data_real telah disortir sehingga tidak ada data anomali/penyusupnya.

Digunakan AND dan OR untuk menemukan data penyusup sesuai kriteria di atas. Dikarenakan kita telah melakukan .copy pada data di atas, maka kolom yang kita buat pada cell sebelumnya ikut terbuat. Maka dari itu, kita hanya membutuhkan kolom-kolom yang relevan dengan data yang kita butuhkan.

# 🎉 Mission Accomplished!

Selamat! Kamu sudah menyelesaikan 10 Misi.
Jangan lupa:
1.  **Kumpulkan di Google Classroom**
2.  Kumpulkan dalam bentuk link colab (Can Edit Access).

Sampai jumpa di Chapter 2!